apiVersion: v1
kind: Service
metadata:
  name: ip-port-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: ip-port-app
  ports:
  - protocol: TCP
    port: 80   # Port exposed on the load balancer
    targetPort: 5000  # Port on which the pods are listening
